name: ci-js-workflow
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: /actions/setup-node
      with:
        node-version: '20.10.0'
    - run: npm test
    - run: node src/index.js