name: ci-js-workflow
on: [push]
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
    - run: npm test
    - run: node src/index.js